### ISSUE TITLE
Dúvidas para licenciamento

### ISSUE THREAD

**Issue by metractive** [anony000/wdd-material#1]
E ai @anony000 , tudo bem?

Sou do grupo de Web Development/Design do WhatsApp e vi que postou. Queria tirar uma dúvida contigo, esses PDF's que postou, são totalmente gratuitos ou existe algum que não é gratuito e exige direito autoral?

Queria me propor para organizar e adicionar licença pra esse repositório.

Fico no teu aguardo.
Abraços, Marcelo.

**Comment by anony000** [comment]
Opá metractive, tudo certo. Então de fato possuí alguns livros que não são gratuítos, no caso são os da Casa do Código o restante pelo o que eu saiba são gratuítos.

**Comment by metractive** [comment]
Mas eles estão licenciados no seu nome, certo?

**Comment by anony000** [comment]
Infelizmente não man, são livros que peguei de links da Internet.

**Comment by anony000** [comment]
Se isso for um problema eu posso remover os livros.

**Comment by metractive** [comment]
Nesse caso, como são livros de direito autoral, é melhor retirar pra não ocorrer dor de cabeça. Se tu puder retirar e me avisar, eu já faço algumas coisas e te mando um pull request. Beleza?

**Comment by metractive** [comment]
Segue licenciamento no Pull Request: #2

**Comment by anony000** [comment]
OK! @metractive  tudo feito.

**Comment by metractive** [comment]
Beleza, mais tarde vou adicionar alguns livros e te mandar mais um PR, beleza?
Ai vou tentar criar um índice. Acho interessante criarmos uns links também.

**Comment by anony000** [comment]
Opá! man beleza! kk Já estava preocupado pensando que ninguém acessaria o repositório hehe

**Comment by metractive** [comment]
Depois de organizado, chamamos a galera lá no WhatsApp. Vou fechar a issue aqui.
