### ISSUE TITLE
Adicionar editores restantes

### ISSUE THREAD

**Issue by metractive** [anony000/wdd-material#4]
@anony000 tudo bem?

Te mandei um PR #3 e nele contém todas as referências e organizei as pastas em uma estrutura de recursos. Onde separei por documentos possíveis de ler e imagens. Podemos ir alimentando nesse mesmo esquema.

Existem documentos que possuem **editor** em negrito e precisava que você editasse o arquivo e adiciona-se os editores restantes.

De qualquer forma, existe bastante material bom ai. Retirei alguns por causa de direito autoral.

**Comment by anony000** [comment]
Opá man pode deixar, tem alguns que não faço a mínima idea de quem seja o editor.

**Comment by metractive** [comment]
Imaginei! Pra isso, a gente pode deixar o editor como desconhecido.

**Comment by anony000** [comment]
OK!
